// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 8);
user_pref("app.normandy.startupRolloutPrefs.services.sync.engine.bookmarks.buffer", true);
user_pref("app.normandy.user_id", "98f8b8e4-b77a-48d5-b94e-91427b2ae523");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1581015920);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1581016040);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1581022219);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1581015680);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1581015560);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1581015800);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1581015470);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1581016160);
user_pref("browser.aboutConfig.showWarning", false);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 54168);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1581015410);
user_pref("browser.laterrun.bookkeeping.sessionCount", 5);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 87);
user_pref("browser.newtabpage.activity-stream.impressionId", "{9e4c7f35-062e-4ede-94b8-38f92a6353e9}");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1581022143288");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1581023915288");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1581025746249");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1581029346249");
user_pref("browser.search.region", "IL");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20191202234414");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1581024732");
user_pref("browser.slowStartup.averageTime", 0);
user_pref("browser.slowStartup.samples", 0);
user_pref("browser.startup.homepage_override.buildID", "20191202234414");
user_pref("browser.startup.homepage_override.mstone", "71.0");
user_pref("browser.startup.lastColdStartupCheck", 1581024733);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1581015412576");
user_pref("distribution.archlinux.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "71.0");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "3a5bac7b500d4d74959efc6e6de04f67");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Thu, 06 Feb 2020 16:14:16 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1581015922);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20191202234414");
user_pref("extensions.lastAppVersion", "71.0");
user_pref("extensions.lastPlatformVersion", "71.0");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"38f88c67-ac58-4769-85ef-fe139a6ec665\",\"screenshots@mozilla.org\":\"d3d41e96-d04f-439f-b8af-91eac99e6634\",\"webcompat-reporter@mozilla.org\":\"c8fd9145-af32-4ddd-ae99-0b33e1e96331\",\"webcompat@mozilla.org\":\"cd0ed75f-4493-4ad6-9dfe-aa077c252f9f\",\"default-theme@mozilla.org\":\"a62bc86f-1c93-4789-a726-28275cc3b7fb\",\"google@search.mozilla.org\":\"41409e7d-7a3b-45ff-98b5-a4e268ca1473\",\"amazondotcom@search.mozilla.org\":\"75127fda-a01f-475f-9da5-512a25b18988\",\"bing@search.mozilla.org\":\"33026007-c46a-4b1f-a306-b6dae90ea787\",\"ddg@search.mozilla.org\":\"1343a7c5-a729-46bd-920b-e57704c89fcd\",\"ebay@search.mozilla.org\":\"b7e72762-7905-40fd-8019-5c82a7581fb3\",\"twitter@search.mozilla.org\":\"2fc6cc9d-5fcf-486a-89e2-af2d4e68756a\",\"wikipedia@search.mozilla.org\":\"99df6cd3-307a-4a5f-8615-d5c77307cde2\"}");
user_pref("media.gmp-gmpopenh264.abi", "x86_64-gcc3");
user_pref("media.gmp-gmpopenh264.lastUpdate", 1581015852);
user_pref("media.gmp-gmpopenh264.version", "1.8.1.1");
user_pref("media.gmp-manager.buildID", "20191202234414");
user_pref("media.gmp-manager.lastCheck", 1581015852);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{05716e2c-890f-4ef8-bad7-b34d8e0c31d7}");
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "6f2353f9-9bb5-47c6-88cf-be806e60a343");
user_pref("security.sandbox.plugin.tempDirSuffix", "a044c86e-2385-4da8-b982-1cfd69cbf9a7");
user_pref("services.settings.clock_skew_seconds", -173);
user_pref("services.settings.last_etag", "\"1581008480228\"");
user_pref("services.settings.last_update_seconds", 1581015973);
user_pref("services.settings.main.anti-tracking-url-decoration.last_check", 1581015973);
user_pref("services.settings.main.cfr-fxa.last_check", 1581015973);
user_pref("services.settings.main.cfr.last_check", 1581015973);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1581015973);
user_pref("services.settings.main.hijack-blocklists.last_check", 1581015973);
user_pref("services.settings.main.language-dictionaries.last_check", 1581015973);
user_pref("services.settings.main.normandy-recipes-capabilities.last_check", 1581015973);
user_pref("services.settings.main.sites-classification.last_check", 1581015973);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1581015973);
user_pref("services.settings.main.whats-new-panel.last_check", 1581015973);
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("services.sync.tabs.lastSync", "0");
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.legacyUserProfileCustomizations.stylesheets", true);
user_pref("toolkit.startup.last_success", 1581024732);
user_pref("toolkit.telemetry.cachedClientID", "e5bf7c2d-21f6-4af0-9c14-9388fbadf0a6");
user_pref("toolkit.telemetry.previousBuildID", "20191202234414");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.extendedTriplets.experiment", "control");
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
user_pref("trailhead.firstrun.interruptsExperiment", "full_page_e");
